global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'
  wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
  wechat_api_corp_id: 'your-corp-id'
  wechat_api_secret: 'your-secret'

templates:
  - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'wechat'
  routes:
    - match:
        severity: critical
      receiver: 'wechat-critical'
    - match:
        severity: warning
      receiver: 'email'

receivers:
  - name: 'wechat'
    wechat_configs:
      - send_resolved: true
        to_party: '1'
        agent_id: 'your-agent-id'
        message: '{{ template "wechat.default.message" . }}'

  - name: 'wechat-critical'
    wechat_configs:
      - send_resolved: true
        to_party: '2'
        agent_id: 'your-agent-id'
        message: '{{ template "wechat.critical.message" . }}'

  - name: 'email'
    email_configs:
      - to: 'team@example.com'
        send_resolved: true
        headers:
          subject: '{{ template "email.default.subject" . }}'
        html: '{{ template "email.default.html" . }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service'] 