global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'

    metric_relabel_configs:
      - source_labels: [mountpoint]
        target_label: filesystem
        regex: '(/.*)'
        replacement: '${1}'

    honor_labels: true
    honor_timestamps: true

    metrics_path: '/metrics'
    scheme: 'http'

    basic_auth:
      username: 'prometheus'
      password: 'password'

    tls_config:
      insecure_skip_verify: false 