groups:
  - name: postgres
    rules:
      # 数据库连接数告警
      - alert: PostgresHighConnections
        expr: pg_stat_activity_count > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL连接数过高"
          description: "数据库连接数超过100"

      # 数据库事务数告警
      - alert: PostgresHighXactCount
        expr: rate(pg_stat_database_xact_commit[5m]) + rate(pg_stat_database_xact_rollback[5m]) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL事务数过高"
          description: "数据库事务数超过1000/s"

      # 数据库缓存命中率告警
      - alert: PostgresLowCacheHitRate
        expr: (pg_stat_database_blks_hit / (pg_stat_database_blks_hit + pg_stat_database_blks_read)) * 100 < 90
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL缓存命中率过低"
          description: "数据库缓存命中率低于90%"

      # 数据库死锁告警
      - alert: PostgresDeadlocks
        expr: rate(pg_stat_database_deadlocks[5m]) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL出现死锁"
          description: "数据库出现死锁情况"

      # 数据库复制延迟告警
      - alert: PostgresReplicationLag
        expr: pg_stat_replication_lag_bytes > 100000000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL复制延迟过高"
          description: "数据库复制延迟超过100MB"

      # 数据库查询时间告警
      - alert: PostgresLongQueries
        expr: pg_stat_activity_max_tx_duration > 300
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL查询时间过长"
          description: "数据库存在执行时间超过5分钟的查询" 